### ISSUE TITLE
讨论：疑惑的是在demo中所有功能都正常，在太记中却有些不同。

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/tiddlywiki-whiteboard#2]
tw-白板版本 0.1.7

Version v0.7.12-prerelease2.

单文件版本和太记的情况是一样的。

**Comment by Zacharia2** [comment]
tw-白板版本 0.1.7

**Comment by linonetwo** [comment]
可能就是因为太记里面依赖的插件还没升级吧，全部升级一下就好了

**Comment by Zacharia2** [comment]
安装的时候看了一眼，没有插件可以升级了

**Comment by linonetwo** [comment]
![](https://user-images.githubusercontent.com/3746270/204750101-2f124e85-ebad-47d6-a563-e7ce7950b6bd.png)

我这里看正常啊

**Comment by linonetwo** [comment]
更新最新版看看，0.2.4了

**Comment by linonetwo** [comment]
原来是 tw-react 构建失败了，我修下

**Comment by Zacharia2** [comment]
大部分可以了

**Comment by Zacharia2** [comment]
![image](https://user-images.githubusercontent.com/32425955/204958501-681d8800-de35-44a8-a9e5-b3a3210f773f.png)

**Comment by Zacharia2** [comment]
![image](https://user-images.githubusercontent.com/32425955/204958920-c9550873-66a5-4841-9041-fda270723ac2.png)

![image](https://user-images.githubusercontent.com/32425955/204959021-b90d538a-80f3-4176-a52b-3f026aabfdaa.png)

**Comment by linonetwo** [comment]
第一个应该是 zindex 层级的问题，好修，第二个不知道咋复现啊

**Comment by linonetwo** [comment]
都是最新版的吗，应该不容易触发报错吧

**Comment by Zacharia2** [comment]
都是最新的，第二个问题随便画画，有几率出现。

**Comment by linonetwo** [comment]
主要的问题是保存后tw刷新，然后微件取最新的覆盖了当前状态，导致状态不一致，出现了没有 type 字段的图形的状态。

![](https://user-images.githubusercontent.com/3746270/205443547-c4acc9c7-a899-4ef9-8b90-50e78c3fd979.png)

![](https://user-images.githubusercontent.com/3746270/205443546-8a8ada5e-2af8-412d-a859-1733a5b58396.png)

![](https://user-images.githubusercontent.com/3746270/205443548-d8529474-78c4-4a56-9727-67d2a91ec59e.png)

大概就是这里是 undefined

具体为啥没空排查了，还好之前做锁定技术的定义器的时候，设计了一个锁的方案，先锁住，反正把那个方案抄过来，应该可以解决问题。

**Comment by Zacharia2** [comment]
赞！

**Comment by linonetwo** [comment]
是一二同学 哈哈
