### ISSUE TITLE
Excalidraw support

### ISSUE THREAD

**Issue by juanitocalero** [tiddly-gittly/tiddlywiki-whiteboard#21]
> If you like excalidraw, and whould like to implement excalidraw as alternative whiteboard enging for this plugin, please rise an issue about it.

It would be great to be able to use Excalidraw as the whiteboard engine. Tldraw has some features missing that I consider basic, like two-headed arrows or library objects.

**Comment by linonetwo** [comment]
https://news.ycombinator.com/item?id=29266164 Excalidraw based on canvas, is not good at rendering wikitext.
