### ISSUE TITLE
鼠标框选位置错位

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/tiddlywiki-whiteboard#26]
现在什么情况会有错位？

- 新建白板条目，绘制一两个图形，保存下来。
- 关闭这个条目，在重新打开。
- 鼠标框选图形，错位复现。

![image](https://user-images.githubusercontent.com/32425955/209456613-6fd17014-7387-43eb-9821-9260dcf4ee6b.png)

**Comment by linonetwo** [comment]
最新master 分支可能没这问题，不过还不支持嵌入条目

**Comment by Zacharia2** [comment]
好滴

**Comment by Zacharia2** [comment]
是的，master分支是正常的。
