### ISSUE TITLE
bug: 画板中箭头无法设置在便签之上，置顶选项无效

### ISSUE THREAD

**Issue by sisyphus1212** [tiddly-gittly/tiddlywiki-whiteboard#39]
### Environment 环境信息

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/45515761/3ca38162-3c51-4a3a-9bde-de1e1ca89089)

### Description 描述

画板中箭头无法设置在便签之上，置顶选项无效

### Steps to Reproduce 复现方式

win10 

### Additional Context 额外上下文

画板中箭头无法设置在便签之上，置顶选项无效

**Comment by linonetwo** [comment]
在 https://github.com/tldraw/tldraw 社区问吧，这纯 tldraw 的用法问题。

**Comment by sisyphus1212** [comment]
这因该是bug，单独使用没问题
