### ISSUE TITLE
插件应自带一个示例条目

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/tiddlywiki-whiteboard#41]
因为没有自带的示例条目，我直接使用侧边栏里的布局切换器，选择白板后，发现什么也没有。然后又没有回退到默认视图的按钮。

检查了半天才发现，首先要有一个白板条目才能正常展示，上面有一个切换白板条目的选择器。

或者在插件的readme中提示一下，要首先建立一个白板条目才能使用侧边栏的布局切换器编辑。

白板插件变得好用多了。以后画流程图就直接用白板插件了。

**Comment by linonetwo** [comment]
的确可以放一个白板，用嵌入的方式实现中英文翻译，然后箭头指向左上角的菜单说明那边可以创建新白板
