### ISSUE TITLE
那看来主要就是涉及到从编辑状态切换出去和切换进来的时候，就都有可能错位。

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/tiddlywiki-whiteboard#5]
之前的版本就是直接在预览状态下就能编辑，所以就没这问题。既然是看论坛上有人说最好像其他条目一样，默认只读，然后编辑状态下才能改。所以加了这个切换看看就出了问题了。

**Comment by Zacharia2** [comment]
这个现在是咋触发呀？我新建也没有这种情况了

我是新建条目后选白板条目类型，随便画上几笔，然后保存就出现了。

另一种情况是点bo白板按钮，进入全屏模式，然后返回预览点击编辑条目按钮。

**Comment by Zacharia2** [comment]
（两个问题的组合，笔触与鼠标位置的不一致，还有显示的问题）

**Comment by linonetwo** [comment]
点bo白板按钮，进入全屏模式，然后返回预览点击编辑条目按钮

这种比较容易触发，看开发者工具可以看到，该有的样式没了

![截屏2022-12-15 14 46 02](https://user-images.githubusercontent.com/3746270/207791555-572440b7-7e5c-4488-8b56-da5c9f9d29e3.png)

而刷新页面直接新建，是有样式表的

![截屏2022-12-15 14 47 06](https://user-images.githubusercontent.com/3746270/207791721-c3ba8064-942a-4120-bdba-b36ffae234c5.png)

看来切换 layout 后，影响了tldraw注入 tl-absolute tl-canvas 的样式

**Comment by linonetwo** [comment]
具体为啥，可能是切换layout后影响了 tldraw 用的 css 库？反正可能需要完全重置一下 tldraw ，有空再研究

**Comment by Zacharia2** [comment]
0.3.4好像解决了显示的问题，太棒了！不过还有一个笔触错位的情况。

**Comment by linonetwo** [comment]
我把 css 放到一个 tiddler 里，避免了被 tldraw 卸载掉。

现在什么情况会有错位？我是没法复现了

**Comment by Zacharia2** [comment]
在太记中就是切换的时候，第一次创建并保存（显示状态正常），再次从显示状态到编辑状态到显示状态，默认的框选工具随便移动就可以看到。不过画笔工具倒是没出错过。
